package com.example.urduphotodesigner.common.canvas.enums

enum class PickerTarget {
  EYE_DROPPER_BACKGROUND,
  EYE_DROPPER_TEXT_FILL,
  EYE_DROPPER_TEXT_STROKE,
  EYE_DROPPER_SHADOW,
  EYE_DROPPER_LABEL,
  EYE_DROPPER_GRADIENT,
  COLOR_PICKER_BACKGROUND,
  COLOR_PICKER_TEXT_FILL,
  COLOR_PICKER_TEXT_STROKE,
  COLOR_PICKER_SHADOW,
  COLOR_PICKER_LABEL,
  COLOR_PICKER_GRADIENT
}